{{- if eq "false" .Values.saas_deployment }}
---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-ui
  labels:
    {{- include "threatstryker-saas.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-ui
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "threatstryker-saas.selectorLabels" . | nindent 4 }}
    name: deepfence-ui

  ports:
    - name: deepfence-ui-port
      port: 4042
      protocol: TCP
      targetPort: 4042
{{- end }}