apiVersion:  apps/v1
kind: Deployment
metadata:
  name: vulnerability-mapper-{{ include "threatstryker-saas.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "threatstryker-saas.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-vulnerability-mapper
spec:
  {{- if not .Values.vmapper.autoscaling.enabled }}
  replicas: {{ .Values.vmapper.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: deepfence-vulnerability-mapper
      {{- include "threatstryker-saas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-vulnerability-mapper
        {{- include "threatstryker-saas.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
      - image: "{{ .Values.vmapper.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.vmapper.image.pullPolicy }}
        name: deepfence-vulnerability-mapper
        ports:
        - containerPort: 8001
        {{- if eq "true" .Values.saas_deployment }}
        env:
            - name: CUSTOMER_UNIQUE_ID
              valueFrom:
                secretKeyRef:
                  name: "es-secret-{{ include "threatstryker-saas.fullname" . }}"
                  key: es_customer_unique_id
        {{- end }}
