---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-internal-router
  labels:
    {{- include "threatstryker-saas.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-internal-router
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "threatstryker-saas.selectorLabels" . | nindent 4 }}
    name: deepfence-internal-router
  ports:
  - name: https-port
    port: 443
    protocol: TCP
    targetPort: 443