apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    app: deepfence-console
    {{- include "threatstryker-saas.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
